<a href="https://colab.research.google.com/github/gabriel-menr/AprendendoPython/blob/main/Aula_alura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercicios do alura


# LISTAS

In [ ]:
dados = [['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
# o conteudo de um lista é denominado pelo oq esta dentro dos[]

In [ ]:
dados

In [ ]:
type(dados)
# a função type mostra o tipo dos dados indicados entre ()

In [ ]:
[i**2 for i in range(30)]
# o ** indicam uma potencia e o for indica um looping 

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841]

In [ ]:
banana = list(set([itens for lista in dados for itens in lista]))

banana

['Sensor de estacionamento',
 'Ar condicionado',
 'Teto panorâmico',
 '4 X 4',
 'Painel digital',
 'Câmera de estacionamento',
 'Central multimídia',
 'Vidros elétricos',
 'Câmbio automático',
 'Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Freios ABS',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Controle de estabilidade']

In [ ]:
banana.sort()
banana

['4 X 4',
 'Ar condicionado',
 'Bancos de couro',
 'Central multimídia',
 'Controle de estabilidade',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Freios ABS',
 'Painel digital',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Teto panorâmico',
 'Travas elétricas',
 'Vidros elétricos']

In [ ]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

# **Usando IF**

In [ ]:
dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False],
    ['uno',2000,True]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False],
 ['uno', 2000, True]]

In [ ]:
dados.sort()
dados

[['A5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Carens', 2011, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Jetta Variant', 2003, False],
 ['Palio Weekend', 2012, False],
 ['Passat', 1991, False],
 ['Série 3 Cabrio', 2009, False],
 ['uno', 2000, True]]

In [ ]:
carro0 = []
carroUsado = []
for lista in dados:
            if(lista[2]== True):
                carro0.append(lista)
            else:
                carroUsado.append(lista)

In [ ]:
carro0

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
carroUsado

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
carros2000, carros1900  = [],[]
for lista in dados:
  if (lista[1]>= 2000):
      carros2000.append(lista)
  else :
    carros1900.append(lista)
carros2000


[['A5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Carens', 2011, False],
 ['DS5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Jetta Variant', 2003, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['uno', 2000, True]]

In [ ]:
carros1900

[['Crossfox', 1990, False], ['Passat', 1991, False]]

# **NUMPY**

In [ ]:
import numpy as np

# importa a biblioteca numpy do python e apelida ela de np

In [ ]:
km = np.array([44410.,5712.,37123.,0.,25757.])
anos = np.array([2003,1991,1990,2019,2006])
# a função numpy.array([]) cria um array 

In [ ]:
idade = 2019 - anos
idade

array([16, 28, 29,  0, 13])

In [ ]:
km_media = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
km_media 


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [ ]:
contador = np.arange(10)
contador
#a função numpy.arange() cria um array com uma sequencia de numeros em ordem crescente que começa no 0
 #e termina no numero anterior ao indicado dentro dos ()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dados = np.array([km,anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[0,2]
# pega a terceira coluna da primeira linha. lembrando que arrays e listas começao da posição 0 

37123.0

In [ ]:
dados[:,1:4]
# o primeiro dado que no caso é o ':' significa o intervalo de linhas que sera usado e apos a virgula é indicado o intervalo de colunas que sera usado 

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [ ]:
contador > 5
# mostra em formato booleano como resposta a condição iposta 

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador>5]
#é possivel fazer uma condição dentro de  uma pesquisa em um array

array([6, 7, 8, 9])

array[inicio:fim:passo, inicio:fim:passo]

Antes da vírgula refere-se às linhas, após a vírgula refere-se às colunas.

Para linhas e colunas temos que:

* início: Se não for especificado começa em 0
* fim: Se não for especificado vai até o fim das linhas ou colunas do array. Se for especificado vai até o número especificado menos 1, pois o fim é não incluso.
* Passo: Parâmetro não obrigatório. Refere-se ao passo que será adotado no fatiamento. Pode ser adotado tanto nas linhas como nas colunas.






In [ ]:
dados.shape
# a função shape mostra quantas linhas e colunas tem no array

(2, 5)

In [ ]:
dados.ndim
# mostra quantas dimenções o array tem. Como nesse caso tem linhas e colunas, logo tem duas dimensões  

2

In [ ]:
dados.size
# mostra o numero de elementos em um array

10

In [ ]:
dados.dtype
# mostra qual o tipo de dados do array. Lembrando que um array so pode ter um tipo de dado

dtype('float64')

In [ ]:
dados.T
#essa função trasforma (traspõe) linhas em colunas. O nome do metodo completo é .traspose

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [ ]:
dados.tolist()
# trasforma um array em uma lista

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [ ]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador.reshape((5, 2))
# muda o formato do array pelo oq foi indicado entre parenteses (linhas,colunas)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5, 2), order = 'c')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5, 2), order = 'f')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
info_carros = km + anos
info_carros

array([46413.,  7703., 39113.,  2019., 27763.])

In [ ]:
km

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
anos

array([2003, 1991, 1990, 2019, 2006])

# **Tests com for**

In [ ]:
verificador = x 
for x in range(0,10,3):
  print(x)
  


0
3
6
9


In [ ]:
num = int(input('Digite um número inteiro:'))
tot = 0
for c in range(1, num + 1):
    if num % c == 0:
        print('\033[34m', end='')
        tot += 1
    else:
        print('\033[31m', end='')
    print('{} '.format(c), end='')
print('\n\033[33mO número {} foi divisivel {} vezes'.format(num, tot))
if tot == 2:
    print('\033[34mEste número é primo!!')
else:
    print('\033[31mEste número não é primo!')
    

Digite um número inteiro:2
1 2 
O número 2 foi divisivel 2 vezes
Este número é primo!!


In [ ]:
num = 10
tot = 0
for c in range(0, num):
    if num >=:
        c = c + 3
        print(c)
    

3
4
5
6
7
8
9
10
11
12


# **Curso 2 alura**

In [ ]:
import pandas as pd
#importa a biblioteca pandas

In [ ]:
dataset = pd.read_csv('/content/sample_data/db.csv',sep = ';') 

In [ ]:
dataset

Nome                  Motor   Ano  Quilometragem  \
0            Jetta Variant        Motor 4.0 Turbo  2003        44410.0   
1                   Passat           Motor Diesel  1991         5712.0   
2                 Crossfox        Motor Diesel V8  1990        37123.0   
3                      DS5        Motor 2.4 Turbo  2019            NaN   
4         Aston Martin DB4        Motor 2.4 Turbo  2006        25757.0   
..                     ...                    ...   ...            ...   
253           Phantom 2013               Motor V8  2014        27505.0   
254  Cadillac Ciel concept               Motor V8  1991        29981.0   
255             Classe GLK  Motor 5.0 V8 Bi-Turbo  2002        52637.0   
256       Aston Martin DB5           Motor Diesel  1996         7685.0   
257                  Macan        Motor Diesel V6  1992        50188.0   

     Zero_km                                         Acessórios      Valor  
0      False  ['Rodas de liga', 'Travas elétricas', 'Piloto ...   88078.64  
1      False  ['Central multimídia', 'Teto panorâmico', 'Fre...  106161.94  
2      False  ['Piloto automático', 'Controle de estabilidad...   72832.16  
3       True  ['Travas elétricas', '4 X 4', 'Vidros elétrico...  124549.07  
4      False  ['Rodas de liga', '4 X 4', 'Central multimídia...   92612.10  
..       ...                                                ...        ...  
253    False  ['Controle de estabilidade', 'Piloto automátic...   51759.58  
254    False  ['Bancos de couro', 'Painel digital', 'Sensor ...   51667.06  
255    False  ['Rodas de liga', 'Controle de tração', 'Câmbi...   68934.03  
256    False  ['Ar condicionado', '4 X 4', 'Câmbio automátic...  122110.90  
257    False  ['Central multimídia', 'Teto panorâmico', 'Vid...   90381.47  

[258 rows x 7 columns]